### ISSUE TITLE
For use in Outside Frameworks/Solutions?

### ISSUE THREAD

**Issue by cody1024d** [Malinskiy/adam#50]
Hello,

I've been prototyping/evaluating this framework for use in an internal testing-harness.

However, I'm seeing various features/functionalities that may do not seem to be working as intended.  I know this was mostly created for use with Marathon, but I was wondering if you'd like me to report the various features/issues I'm seeing?

Thanks,
Cody

**Comment by Malinskiy** [comment]
Hey @cody1024d
Adam is completely independent from marathon and is a replacement for ddmlib, so if something is not working as intended - please report it. 

Thanks for your feedback!
