### ISSUE TITLE
Individual Test Metrics are not reported

### ISSUE THREAD

**Issue by cody1024d** [Malinskiy/adam#51]
Based on the DDMLib documentation:

```
com.android.ddmlib.testrunner.ITestRunListener void testEnded(TestIdentifier test,
               Map<String, String> testMetrics)
Reports the execution end of an individual test case.
If testFailed was not invoked, this test passed. Also returns any key/value metrics which may have been emitted during the test case's execution.

Params:
test – identifies the test
testMetrics – a Map of the metrics emitted during the execution of the test case by android.app.Instrumentation#sendStatus. The insertion order is preserved unless you emit a same key multiple times. Note that standard keys defined in IInstrumentationResultParser.StatusKeys are filtered out of this Map. Ddmlib may add extra test metrics defined in IInstrumentationResultParser.StatusKeys.
```

Based on the code found in the `InstrumentationResponseTransformer`, it looks like this isn't happening.  Looking at how the data is being handled once received, it looks like nothing is happening in a "PROGRESS" status. Our client code is sending a bunch of metadata with a "PROGRESS" status, and then expecting the metrics to be collected and sent with the TEST-END event.  Looks like no matter what is received, the metrics just stay as an empty map (line 141).

I've also investigated a bit with the `ProtoInstrumentationResponseTransformer`. And while it does properly "cache" the metrics that come across while the test is running, it never sends a TestEnd event, in the case of a successful status code being sent (line 230 --- isTerminal returns false if it's a SUCCESS status code)

Thanks,
Cody

**Comment by Malinskiy** [comment]
Thanks for highlighting this. Would you be able to submit an input file and expected events similar to what's found in the https://github.com/Malinskiy/adam/tree/master/adam/src/test/resources/instrumentation?

Thanks

FYI: proto [should not be used](https://malinskiy.medium.com/android-am-instrument-proto-test-result-architecture-review-790652b6a202) by anyone in my opinion

**Comment by cody1024d** [comment]
@Malinskiy Is there a good (easy) way to generate the input file? 

Can I run an ADB AM command with a flag or something to get it to generate it?

**Comment by Malinskiy** [comment]
The input is just stdout of 'adb shell am instrument'

**Comment by cody1024d** [comment]
Here is the input info:
```
INSTRUMENTATION_STATUS: class=com.bofa.android.adapoc.home.HomeActivityTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.bofa.android.adapoc.home.HomeActivityTest:
INSTRUMENTATION_STATUS: test=verify01_homeActivity_displayed
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: description=TestDescription
INSTRUMENTATION_STATUS: displayName=TestDisplayName
INSTRUMENTATION_STATUS: dsaProfileName=FooBar
INSTRUMENTATION_STATUS: module=FooBar
INSTRUMENTATION_STATUS: storyIdentifier=TestIdentifier
INSTRUMENTATION_STATUS: testIdentifier=Ex-1023
INSTRUMENTATION_STATUS_CODE: 2
INSTRUMENTATION_STATUS: class=com.bofa.android.adapoc.home.HomeActivityTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: test=verify01_homeActivity_displayed
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_RESULT: stream=

Time: 17.084

OK (1 test)


INSTRUMENTATION_CODE: -1
```

You'll see the status_code:2, and the misc. metrics come across in the middle there

Thanks,
Cody
