### ISSUE TITLE
Logcat streaming buffer issue for large logs (clipping logs)

### ISSUE THREAD

**Issue by amank22** [Malinskiy/adam#68]
Streaming Logcat will return data in chunks but it's not really possible to stream lines. The buffer end could be between anywhere and not really possible if someone wants to work on per-line basis.
This is I think because of the BufferPools in case of large logs.

**Describe alternatives you've considered**
[See ddmlib implementation](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:ddmlib/src/main/java/com/android/ddmlib/logcat/LogCatReceiverTask.java)

**Comment by Malinskiy** [comment]
Hey @amank22 

I'm not sure what's the issue here: the adb protocol doesn't allow you to stream the output of a terminal command line by line, so the only option if you want to parse lines separately, is to accumulate all the data in a buffer then split it into lines and then parse them however you want.

The buffer end for a single string in theory could be infinite, but there is a commonly-used limit on the string that you can pass to the Log.x call from the Android's side (if I understood your question correctly). On top of this, the adb protocol will frame the output so that you don't receive for example 5Mb in one go over the TCP socket (I believe the usual limit now is 256K for a single chunk between adb server and adbd for most of the new devices, but that depends on the device and adb server implementation at hand).

Could you please provide an example code of how you're trying to achieve the per-line parsing and describe what is not working for you as expected?

Thanks

**Comment by amank22** [comment]
So let's say the actual logs are as following:
```
01-06 14:39:19.646  2912  2915 D IHansComunication: sendMsgToFW--type: 0, callerPid: 1816, targetUid: 10348
01-06 14:39:19.649  2912  2915 D IHansComunication: HANS handleMessage: Got message from kernel
01-06 14:39:19.649  2912  2915 E IHansComunication: HANS printMessageBody: RCVed message body: type = 0, port = 86870, caller_pid = 1816, target_uid = 10320, pkg_cmd = -1
01-06 14:39:19.649  2912  2915 D IHansComunication: sendMsgToFW--type: 0, callerPid: 1816, targetUid: 10320
01-06 14:39:19.650 31269 31357 I BtGatt.ScanManager: msg.what = 8
01-06 14:39:19.650 31269 31357 I BtGatt.ScanManager: msg.what = 5
01-06 14:39:19.652 27561 27561 D TouchInteractionService: onDisplayChanged displayId = 0, mDefaultDisplayId = 0
01-06 14:39:19.655  2912  2915 D IHansComunication: HANS handleMessage: Got message from kernel
01-06 14:39:19.655  2912  2915 E IHansComunication: HANS printMessageBody: RCVed message body: type = 0, port = 86870, caller_pid = 1816, target_uid = 10245, pkg_cmd = -1
01-06 14:39:19.655  2912  2915 D IHansComunication: sendMsgToFW--type: 0, callerPid: 1816, targetUid: 10245

```

Using the streaming apis:
```
val channel = adb.execute(
        request = ChanneledLogcatRequest(),
        scope = this,
        serial = "emulator-5554"
    )

    val line = channel.receive()
    //write to a file...
```

So there is a change that I would get response broken like below:
1.)
```
01-06 14:39:19.646  2912  2915 D IHansComunication: sendMsgToFW--type: 0, callerPid: 1816, targetUid: 10348
01-06 14:39:19.649  2912  2915 D IHansComunication: HANS handleMessage: Got message from kernel
01-06 14:39:19.649  2912  2915 E IHansComunication: HANS printMessageBody: RCVed message body: type = 0, port = 86870, caller_pid = 1816, target_uid = 10320, pkg_cmd = -1
01-06 14:39:19.649  2912  2915 D IHansComunication: sendMsgToFW--type: 0, callerPid: 1816, targetUid: 10320
01-06 14:39:19.650 31269 31357 I BtGatt
```
2.)
```
.ScanManager: msg.what = 8
01-06 14:39:19.650 31269 31357 I BtGatt.ScanManager: msg.what = 5
01-06 14:39:19.652 27561 27561 D TouchInteractionService: onDisplayChanged displayId = 0, mDefaultDisplayId = 0
01-06 14:39:19.655  2912  2915 D IHansComunication: HANS handleMessage: Got message from kernel
01-06 14:39:19.655  2912  2915 E IHansComunication: HANS printMessageBody: RCVed message body: type = 0, port = 86870, caller_pid = 1816, target_uid = 10245, pkg_cmd = -1
01-06 14:39:19.655  2912  2915 D IHansComunication: sendMsgToFW--type: 0, callerPid: 1816, targetUid: 10245
```

This breaking of logs at the end is what my issue is. Even if I break the text into lines, the last line is issue for me which I am not sure if it's a complete line.

Not sure where the issue might be.

**Comment by Malinskiy** [comment]
The streaming API does not provide a response as separated lines. You should combine the resulting string in an accumulator first as mentioned above.
I suspect you're confused and expect all the results from a `receive()` call to return a '\n' terminated string. That is not the case.

So suppose you have a response that consists of: `Line 1: abcdefg` and `hijklmnop\nLine 2: 123456` and `7890\n`. In order for you to receive the line you accumulate everything, for example in a string buffer. Then after each append you verify if you indeed accumulated at least one line by the presence of `\n`, then process separated lines.

Just to reiterate: please append everything to some kind of buffer and check it for the presence of a line terminator to get the behaviour that you want. Do not use the raw responses: they're not lines, but they do contain line termination characters.

**Comment by amank22** [comment]
Yes, that I am not assuming it to be single lines and taking it as a chunk of lines that needs processing of some kind.
That buffer/queue needs to be done. Thanks for that. :)

Also if we can document the behaviour, it will be helpful for others.

Also, thanks for the hard work you have done on this.
We can close this issue I think.

**Comment by Malinskiy** [comment]
Sure thing. I'll close the issue after the update to the docs. Thanks for creating the ticket :)
