### ISSUE TITLE
Screenshot not working ig

### ISSUE THREAD

**Issue by CrazyJannis44** [Malinskiy/adam#90]
![grafik](https://user-images.githubusercontent.com/36644360/198907352-1ac70551-dcee-444d-b781-a7106eb4cde2.png)
![grafik](https://user-images.githubusercontent.com/36644360/198907368-50a2a44c-bcae-40e3-944b-045ad533cc55.png)

**Comment by Malinskiy** [comment]
https://malinskiy.github.io/adam/docs/screen-capture/screenshot/

**Comment by CrazyJannis44** [comment]
Also doesnt work if i use RawImageScreenCaptureAdapter() instead of BufferedImageScreenCaptureAdapter and then do .toBufferedImage()
or is providing the serial id necessary?

**Comment by Malinskiy** [comment]
The serial is a required parameter. There are no assumptions about the target device, so you have to specify the serial

Please read the docs, in particular, https://malinskiy.github.io/adam/docs/caveats/#request-target

**Comment by Malinskiy** [comment]
I assume you've solved the issue. If not - please reopen with more information.
