### ISSUE TITLE
Cannot install an APK with streaming file

### ISSUE THREAD

**Issue by hamidness** [Malinskiy/adam#96]
**Describe the bug**
I couldn't install an APK file on a connected emulator with StreamingPackageInstallRequest request. it returns false always without any exception, without installing the package.

**To Reproduce**
```kotlin
adb.execute(
  request = StreamingPackageInstallRequest(
    pkg = File(apkFilename),
    supportedFeatures = listOf(Feature.CMD),
    reinstall = true,
    extraArgs = emptyList()
  ),
  serial = "emulator-5554"
)
```

**Android device (please complete the following information):**
 - Device: Android Emulator
 - OS: Any 
 - Adam Version 0.5.0
 - ADB version 33.0.3-8952118

**Comment by Malinskiy** [comment]
Does your device really support cmd feature? Can you please confirm Android OS version

**Comment by hamidness** [comment]
The Android OS version: 12

I received these supported features by the emulator:
SHELL_V2, CMD, STAT_V2, LS_V2, FIXED_PUSH_MKDIR, APEX, ABB, FIXED_PUSH_SYMLINK_TIMESTAMP, ABB_EXEC, REMOUNT_SHELL, TRACK_APP, SENDRECV_V2, SENDRECV_V2_BROTLI, SENDRECV_V2_LZ4, SENDRECV_V2_ZSTD, SENDRECV_V2_DRY_RUN_SEND

So it seems the emulator supports CMD feature
